import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class loginPage extends javax.swing.JFrame {
    int check = 0;
    String u, p;
    public loginPage() {
        initComponents();

        userStaff.setVisible(false);
        passStaff.setVisible(false);
        passStud.setVisible(false);
        userStud.setVisible(false);
        login.setVisible(false);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("Sim-GE.png"));
        Image img = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
        SIMlogo.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPane = new javax.swing.JPanel();
        registration = new javax.swing.JButton();
        userStaff = new javax.swing.JTextField();
        passStaff = new javax.swing.JPasswordField();
        userStud = new javax.swing.JTextField();
        passStud = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        SIMlogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPane.setBackground(new java.awt.Color(244, 249, 244));
        LoginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registration.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        registration.setForeground(new java.awt.Color(153, 0, 0));
        registration.setText("Register");
        registration.setBorderPainted(false);
        registration.setContentAreaFilled(false);
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        LoginPane.add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        userStaff.setForeground(new java.awt.Color(204, 204, 204));
        userStaff.setText("username");
        userStaff.setToolTipText("enter your username!");
        userStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userStaffMouseClicked(evt);
            }
        });
        userStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userStaffActionPerformed(evt);
            }
        });
        LoginPane.add(userStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, -1));

        passStaff.setForeground(new java.awt.Color(204, 204, 204));
        passStaff.setText("password");
        passStaff.setToolTipText("enter your password!");
        passStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passStaffMouseClicked(evt);
            }
        });
        passStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passStaffActionPerformed(evt);
            }
        });
        LoginPane.add(passStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, -1));

        userStud.setForeground(new java.awt.Color(204, 204, 204));
        userStud.setText("username");
        userStud.setToolTipText("enter your username!");
        userStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userStudMouseClicked(evt);
            }
        });
        userStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userStudActionPerformed(evt);
            }
        });
        LoginPane.add(userStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, -1));

        passStud.setForeground(new java.awt.Color(204, 204, 204));
        passStud.setText("password");
        passStud.setToolTipText("enter your password!");
        passStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passStudMouseClicked(evt);
            }
        });
        passStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passStudActionPerformed(evt);
            }
        });
        LoginPane.add(passStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, -1));

        login.setBackground(new java.awt.Color(242, 247, 242));
        login.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        login.setText("Login");
        login.setToolTipText("click to login!");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        LoginPane.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel1.setBackground(new java.awt.Color(242, 247, 242));
        jLabel1.setFont(new java.awt.Font("Palace Script MT", 0, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("Booking System");
        LoginPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Staff", "Student" }));
        jComboBox1.setToolTipText("what are you...?");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        LoginPane.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, -1));

        SIMlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SIMlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sim-GE.png"))); // NOI18N
        SIMlogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LoginPane.add(SIMlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -60, 380, 350));

        getContentPane().add(LoginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (check == 1) {
        
            int val = 0;
            fileStaff f = new fileStaff();
            
            try {
                val = f.fileStaff1(userStaff.getText(),passStaff.getText());
            } 
            
            catch (IOException ex) {
                Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (val == 1){
               JOptionPane.showMessageDialog(null, "Successful login!", "Login Success", JOptionPane.INFORMATION_MESSAGE);
                staffPage s = null;
                try {
                    s = new staffPage();
                } 
                
                catch (IOException ex) {
                    Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                s.setVisible(true);
                loginPage.this.setVisible(false);
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Wrong username and/or password!", "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }

        else if(check == 2){
            int val = 0;
            studentFile f = new studentFile();
            
            try {
                val= f.studentFile1(userStud.getText(),passStud.getText());
            } 
            
            catch (IOException ex) {
                Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (val == 1){
                JOptionPane.showMessageDialog(null, "Successful login!", "Login Success", JOptionPane.INFORMATION_MESSAGE);
                try {
                    new studentHomePage().setVisible(true);
                } 
                
                catch (IOException ex) {
                    Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                loginPage.this.setVisible(false);
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Wrong username and/or password!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Wrong username and/or password!", "Error", JOptionPane.ERROR_MESSAGE);
            //jComboBox1ActionPerformed(evt);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String itemSelected = jComboBox1.getSelectedItem() + "";
        
        if (itemSelected.equals("Staff")) {
            passStud.setVisible(false);
            userStud.setVisible(false);
            userStaff.setVisible(true);
            passStaff.setVisible(true);
            login.setVisible(true);
            check = 1;
        }
        
        else if (itemSelected.equals("Student")) {
            userStaff.setVisible(false);
            passStaff.setVisible(false);
            passStud.setVisible(true);
            userStud.setVisible(true);
            login.setVisible(true);
            check = 2;
        }
        
        else {
            userStaff.setVisible(false);
            passStaff.setVisible(false);
            passStud.setVisible(false);
            userStud.setVisible(false);
            login.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void userStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userStaffMouseClicked
        userStaff.setText(null);
        userStaff.setForeground(Color.black);
    }//GEN-LAST:event_userStaffMouseClicked

    private void passStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passStaffMouseClicked
        passStaff.setText(null);
        passStaff.setForeground(Color.black);
    }//GEN-LAST:event_passStaffMouseClicked

    private void userStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userStudMouseClicked
        userStud.setText(null);
        userStud.setForeground(Color.black);
    }//GEN-LAST:event_userStudMouseClicked

    private void passStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passStudMouseClicked
        passStud.setText(null);
        passStud.setForeground(Color.black);
    }//GEN-LAST:event_passStudMouseClicked

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        new registration().setVisible(true);
    }//GEN-LAST:event_registrationActionPerformed

    private void userStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userStaffActionPerformed
        u = userStaff.getText();
    }//GEN-LAST:event_userStaffActionPerformed

    private void passStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passStaffActionPerformed
        p = passStaff.getText();
    }//GEN-LAST:event_passStaffActionPerformed

    private void userStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userStudActionPerformed
        u = userStud.getText();
    }//GEN-LAST:event_userStudActionPerformed

    private void passStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passStudActionPerformed
        p = passStud.getText();
    }//GEN-LAST:event_passStudActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPane;
    private javax.swing.JLabel SIMlogo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passStaff;
    private javax.swing.JPasswordField passStud;
    private javax.swing.JButton registration;
    private javax.swing.JTextField userStaff;
    private javax.swing.JTextField userStud;
    // End of variables declaration//GEN-END:variables
}

class studentFile extends loginPage{
    String ps,un;
    String [] line;
    String studentfile = directory.student; 
    
    public int studentFile1(String u, String p)throws IOException{
        Scanner input = new Scanner (new File(studentfile));
        String str, id;
        
        while (input.hasNextLine()) {
            str = input.nextLine();
            line = str.split(",");
            un = line[0];
            ps = line[1];
            id = line[2];
            userID userID = new userID();
            userID.setID(id);
            
            if ((ps.equals(p)) && (un.equals(u))){
                return 1;
            }
        }
           
        return 2;
    }
}

class fileStaff extends loginPage {
    String ps,un;
    String [] line;
    String stafffile = directory.staff;
    
    public int fileStaff1(String u, String p) throws IOException{
        Scanner input = new Scanner (new File(stafffile));
        String str, id;
        
        while (input.hasNextLine()) {
            str = input.nextLine();
            line = str.split(",");
            un = line[0];
            ps = line[1];
            id = line[2];
            userID userID = new userID();
            userID.setID(id);
            if((ps.equals(p)) && (un.equals(u))){ 
                return 1;
            } 
        }
        return 2;
    }
}