import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class staffPage extends javax.swing.JFrame {
    File folder = new File (directory.file);
    
    public staffPage() throws IOException {
       initComponents();
       
        try {
            getInfo();
        } 
        
        catch (FileNotFoundException ex) {
            Logger.getLogger(staffPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getInfo() throws FileNotFoundException, IOException{
        File[] listOfFiles = folder.listFiles();
        String id = String.valueOf(userID.getID());
        
        for (File file : listOfFiles) {
            String n = file.getPath();
            if (file.isFile()) {
                if (n.contains(id)) {
                    String fileN = file.getPath();
                    BufferedReader br = new BufferedReader(new FileReader(fileN));
                    Object[]tableLines = br.lines().toArray();
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

                    for (int i = 0; i < 1; i++) {
                        String line = tableLines[i].toString().trim();
                        String[] dataRow = line.split(",");
                        model.addRow(dataRow);
                    }
                    br.close();    
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewEvents = new javax.swing.JButton();
        myEvents = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        staffPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkBorderRadius(5);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkGradientFocus(300);
        kGradientPanel2.setkStartColor(new java.awt.Color(113, 199, 172));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Event", "Venue", "Slots"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentY(1.0F);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        kGradientPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 800, 160));

        viewEvents.setBackground(new java.awt.Color(75, 140, 113));
        viewEvents.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        viewEvents.setForeground(new java.awt.Color(255, 255, 255));
        viewEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Eye_64px.png"))); // NOI18N
        viewEvents.setText("View All Events");
        viewEvents.setActionCommand("My Events");
        viewEvents.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        viewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEventsActionPerformed(evt);
            }
        });
        kGradientPanel2.add(viewEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 260, 130));

        myEvents.setBackground(new java.awt.Color(75, 140, 113));
        myEvents.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        myEvents.setForeground(new java.awt.Color(255, 255, 255));
        myEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Checked_64px.png"))); // NOI18N
        myEvents.setText("My Events");
        myEvents.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        myEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myEventsActionPerformed(evt);
            }
        });
        kGradientPanel2.add(myEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 250, 130));

        logout.setBackground(new java.awt.Color(0, 0, 64));
        logout.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Shutdown_28px.png"))); // NOI18N
        logout.setText("Logout");
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        kGradientPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 50));

        staffPage.setFont(new java.awt.Font("Palace Script MT", 0, 80)); // NOI18N
        staffPage.setForeground(new java.awt.Color(255, 255, 255));
        staffPage.setText("Staff Page");
        kGradientPanel2.add(staffPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEventsActionPerformed
        try {
            new staffViewEvents().setVisible(true);
        } 
        
        catch (IOException ex) {
            Logger.getLogger(staffPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        staffPage.this.setVisible(false);        
    }//GEN-LAST:event_viewEventsActionPerformed

    private void myEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myEventsActionPerformed
        try {
            new staffEvents().setVisible(true);
        } 
        
        catch (IOException ex) {
            Logger.getLogger(staffPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        staffPage.this.setVisible(false);
    }//GEN-LAST:event_myEventsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new loginPage().setVisible(true);
        staffPage.this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new staffPage().setVisible(true);
                } 
                
                catch (IOException ex) {
                    Logger.getLogger(staffPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton myEvents;
    private javax.swing.JLabel staffPage;
    private javax.swing.JButton viewEvents;
    // End of variables declaration//GEN-END:variables
}
